#pragma once

#define BCM_CPU_PERIPH_BASE			0x3F000000
#define BCM_BUS_PERIPH_BASE			0x7E000000
#define BCM_CPU_DRAM_BASE			0
#define BCM_BUS_DRAM_BASE			0xC0000000

#define BCM_CPU_TO_BUS_PERIPH_ADDR(x)	(BCM_BUS_PERIPH_BASE + ((ULONG)(x) - BCM_CPU_PERIPH_BASE))
#define BCM_CPU_TO_BUS_DRAM_ADDR(x)		(BCM_BUS_DRAM_BASE + ((ULONG)(x) - BCM_CPU_DRAM_BASE))
